<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "includes/DefaultSettings.php" );
# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

include_once ($IP . '/extensions/di/iwDrupal.php');
# include_once ($IP . '/skins/brlcad/brlcad.php');
# include_once ($IP . '/skins/Brlcadnew.php');


if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}

$wgGroupPermissions['*']['createpage'] = false;

## Uncomment this to disable output compression
$wgDisableOutputCompression = true;

$wgSitename         = "BRL-CAD";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
$wgScriptPath       = "/w";
$wgScriptExtension  = ".php";

## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgArticlePath = "/wiki/$1";

$wgEnableEmail      = true;
$wgEnableUserEmail  = true;

$wgEmergencyContact = "devs@brlcad.org";
$wgPasswordSender = "devs@brlcad.org";

## For a detailed description of the following switches see
## http://meta.wikimedia.org/Enotif and http://meta.wikimedia.org/Eauthent
## There are many more options for fine tuning available see
## /includes/DefaultSettings.php
## UPO means: this is also a user preference option
$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEnotifMinorEdits = true;
$wgEmailAuthentication = true;
$wgUsersNotifiedOnAllChanges = array('brlcad@mac.com');

require_once('/etc/brlcad/betawikisettings.php');

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "TYPE=InnoDB";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

# Postgres specific settings
$wgDBport           = "5432";
$wgDBmwschema       = "mediawiki";
$wgDBts2schema      = "public";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = true;
$wgUseImageResize      = true;
$wgFileExtensions      = array('png','jpg','jpeg','svn','gif','svg');
$wgUploadPath          = "$wgScriptPath/images";
$wgUploadDirectory     = "$IP/images";
$wgUseImageMagick = true;
# $wgImageMagickConvertCommand = "/etc/brlcad/convert";

$wgSVGConverterPath = '/etc/brlcad';

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

# keep changes for a really long time
$wgRCMaxAge = 15724800; // 6 months

$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "en";

$wgProxyKey = "1f8506f970a52aae750b9981693c104e3e23c2082405952f695b1f1867bcd494";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'modern';

# logo for certain error pages
$wgLogo = '../images/logo/BRL-CAD_256x212.png';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

# enable an additional captcha
require_once( "$IP/extensions/ConfirmEdit/ConfirmEdit.php" );
require_once( "$IP/extensions/ConfirmEdit/QuestyCaptcha.php" );
$wgCaptchaClass = 'QuestyCaptcha';
$wgCaptchaQuestions[] = array( 'question' => "What is the official name of this solid modeling software system?", 'answer' => "BRL-CAD" );
$wgCaptchaQuestions[] = array( 'question' => "What is the square root of 100 - 51?", 'answer' => "7" );
$wgCaptchaQuestions[] = array( 'question' => "In what year did BRL-CAD become an Open Source project?", 'answer' => "2004" );
$wgCaptchaQuestions[] = array( 'question' => "What is the sum of all elements in a 4x4 homogenous identity matrix?", 'answer' => "4" );
$wgCaptchaQuestions[] = array( 'question' => "What is the dot product of [2, 12, 1] with [7, 2, 4]?", 'answer' => "42" );
$wgCaptchaQuestions[] = array( 'question' => "How many fingers are you holding up when your hands are in your pocket?", 'answer' => "0" );
$wgCaptchaQuestions[] = array( 'question' => "What is the square root of 200 - 151?", 'answer' => "7" );
$wgCaptchaQuestions[] = array( 'question' => "BRL-CAD uses a right-hand coordinate system.  What is always the correct (x, y, or z) positive axis vector for \"up\"?", 'answer' => "z" );
$wgCaptchaQuestions[] = array( 'question' => "What is the dot product of [1, 2, 1] with [7, 2, 4]?", 'answer' => "15" );
$wgCaptchaQuestions[] = array( 'question' => "What is the sum of all elements in a 3x3 zero matrix?", 'answer' => "0" );
$wgCaptchaQuestions[] = array( 'question' => "What is the square root of 50 + 14?", 'answer' => "8" );
$wgCaptchaQuestions[] = array( 'question' => "Responding true or false, a right-hand coordinate system is better than left-hand for 3D?", 'answer' => "true" );
$wgCaptchaQuestions[] = array( 'question' => "How many fingers are you holding up when your raise you point at a star?", 'answer' => "1" );
$wgCaptchaQuestions[] = array( 'question' => "What is the square root of 1000 - 100?", 'answer' => "30" );
$wgCaptchaQuestions[] = array( 'question' => "What is the dot product of [1, 2, 3, 0] with [3, 2, 1, 1]?", 'answer' => "10" );
$wgCaptchaQuestions[] = array( 'question' => "What is the square root of 50 + 50?", 'answer' => "10" );
$wgCaptchaQuestions[] = array( 'question' => "What is the best open source solid modeling system (uppercase with dash)?", 'answer' => "BRL-CAD" );

#autoconfirmed settings
$wgAutoConfirmCount=3;

#require_once( "$IP/extensions/recaptcha/ReCaptcha.php" );
require_once( "/etc/brlcad/recaptchakeys.php" );
$wgGroupPermissions['autoconfirmed']['skipcaptcha']=true; //allow registered users to skip the captcha triggers
$wgCaptchaTriggers['edit']=true; //force captcha on edit
$wgCaptchaTriggers['create']=true; //force captcha on new page

# let passwords be reset
$wgGroupPermissions['sysop']['passwordreset'] = true;

# turn on my snazzy CIA notifier extension
$cnProject = 'BRL-CAD';
require_once( "$IP/extensions/CIAnotify/CIAnotify.php" );

# enable a spam blacklist extension
ini_set( 'pcre.backtrack_limit', '8M' );

# FIXME: upgrading to 1.22.2 where SpamBlacklist.php is bundled by
# default seems to cause an inf loop in httpd (same happens with old)
# OOF. require_once( "$IP/extensions/SpamBlacklist/SpamBlacklist.php" );
$wgSpamBlacklistFiles = array(
   "[[m:Spam blacklist]]",
   "http://en.wikipedia.org/wiki/MediaWiki:Spam-blacklist"
);

# feed settings
$wgFeedLimit = 100; /* num feed results */
$wgFeedCacheTimeout = 0; /* only keep at 0 for debugging */
$wgFeedDiffCutoff = 131072; /* max size of feed diffs */

$wgDiff3 = "/etc/brlcad/diff3";

$wgFileExtensions[] = 'pdf';

$wgAllowExternalImages = true;

$wgUploadSizeWarning = 1048576;

require_once( "$IP/extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.php" );

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$configdate = gmdate( 'YmdHis', @filemtime( __FILE__ ) );
$wgCacheEpoch = max( $wgCacheEpoch, $configdate );

require_once( "$IP/extensions/SpamRegex/SpamRegex.php" );
$wgGroupPermissions['sysop']['spamregex']=true;
$wgGroupPermissions['bureaucrat']['spamregex']=true;

$wgSpamRegex = "/".
#                "http:\/\/.*\.com|http:\/\/.*\.net|http:\/\/.*[^cC][^aA][^dD]\.org|". # any link to an external site
                "s e x|zoofilia|sexyongpin|grusskarte|geburtstagskarten|animalsex|".
                "sex with|dogsex|adultchat|adultlive|camsex|sexcam|livesex|sexchat|".
                "chatsex|onlinesex|adultporn|adultvideo|adultweb.|hardcoresex|hardcoreporn|".
                "teenporn|xxxporn|lesbiansex|livegirl|livenude|livesex|livevideo|camgirl|".
                "spycam|voyeursex|casino online|online casino|kontaktlinsen|cheapest phone|".
                "laser eye|eye laser|fuelcellmarket|lasikclinic|cragrats|parishilton|".
                "paris hilton|paris tape|2large|fuel dispenser|fueling dispenser|huojia|".
                "jinxinghj|telematicsone|telematiksone|a mortgage|diamondabrasives|".
                "reuterbrook|sex plugin|sex zone|lazy stars|eblja|liuhecai|".
                " viagra| cialis| levitra|boy and girl| cancun|beach hotel|".
                "buywebsitetraffic101|flicktrack|brooksbusinesssystems|scoutify|".
                "virket|seccionamarilla|L carnitine|zayiflamahapi|obesity|".
                "loan|bad credit|quesadillas|monclasseur| dating|net courting|web courting|".
                " SEO |search engine|internet advertising|search engine optimization|". # SEO spam
                "island vacation|tourism|anna maria|termlifequotes|term life|life insurance|".
                "insurance coverage|insurance quote|guaranteed income|renewable|adult webcam|sexual orient|".
                "fire pits| romantic| romance|quickbooks|free checking|financial worr|job opportunit|".
                "replica watch|internet store|online shop|buying online|rolex |concrete floor|epoxy floor|metallic epoxy|polished concrete|".
                "your gold|selling *gold|buying *gold|for gold|fraudulence|health advice| Ferriss|four hour body|".
                "pc clean|cyberdefender|breathing problem|stop cough|stop snor|sneezing|hormonal|medical expert|class action|".
                "personal injury|will attorney|injured |injury |general practitioner|auto accident|video market| sells|marketing manager|".
                "gay video|global market|develop strateg|signage|vacationer|career field|computer screen|businesses|".
                "buy a house|real estate|brokerage|for sale|commercial property|buy used|mildew|weight loss|".
                "slimming pill|junk meal|red meat|lose weight|gaming computer|pc gaming|gaming pc|baler machine| profit|shredding equip|".
                "rental agreement|cpap |jackpot|production sched|operation plan|modern business|".
		"master card|debt settle|debt collect|collect debt|identity theft|credit check|check approval|".
		"inflatable |".
                "elitemachinery|lidasatis|oztac|talkingaboutfamily|mondoy|exactrelease|pr-canada|". #URLS
                "perlengkapan|outsourcing|radionogori|vbc6|credenciamentoeventos|sikhbook|youblisher|crocodoc|mytravelmap|rochestersocial|". # URLS
                "dirare|philoslove|indoirc|pdfcast|youscribe|angelfire|kewego|jalmadaya|guemau|bursariau|myplick|sgmodeling|watch7750|concreteartfx|". # URLS
                "paggreviews|purevolume|posterous.com|shshealth|weebly|saranasukses|littletods|goldenfibreglass|tokobungasabana|ultimatejumpers|". # URLS
                "overflow\s*:\s*auto|".   # This matches against overflow:auto (regardless of whitespace on either side of the colon)
                "height\s*:\s*[0-4]px|".  # This matches against height:0px (most CSS hidden spam) (regardless of whitespace on either side of the colon)
                "==<center>\[|".          # This matches some recent spam related to starsearchtool.com and friends
                "\<\s*a\s*href|".         # This blocks all href links entirely, forcing wiki syntax
                "display\s*:\s*none".     # This matches against display:none (regardless of whitespace on either side of the colon)
                "/i";                     # The "/" ends the regular expression and the "i" switch which follows makes the test case-insensitive
                                          # The "\s" matches whitespace
                                          # The "*" is a repeater (zero or more times)
                                          # The "\s*" means to look for 0 or more amount of whitespace

# convert all instances of space to a more robust variety
#$wgSpamRegex = str_replace(" ", "[[:space:][:punct:]_-]+", $wgSpamRegex);

# limit name lengths to help reduce spam
require_once( "{$IP}/extensions/MinimumNameLength/MinimumNameLength.php" );

# display multipage pdf files 
require_once("$IP/extensions/PdfHandler/PdfHandler.php");

# special page to tell us what needs updating
require_once("$IP/extensions/Update/Update.php");

$wgDebugComments = true;
